Update alexa
nextdns/metadata pull request #829
Opened 2021-11-27 10:40 UTC by Rexadev

2021-11-27 13:25 UTC, rs requested changes

2021-11-27 13:25 UTC, rs commented on privacy/native/alexa
> +mshop-configs.shopping.alexa.a2z.com
This one is covered by previous line

2021-11-27 13:25 UTC, rs commented on privacy/native/alexa
> +aws.a2z.com
This will likely break non alexa stuff

2021-11-27 13:25 UTC, rs commented on privacy/native/alexa
> +redirect.prod.experiment.routing.cloudfront.aws.a2z.com
Same here, does look like alexa specific

2022-12-11 22:57 UTC, romaincointepas commented
Those may break some features.

2022-12-11 22:57 UTC, closed without merging